[[providers]]
name = "infisical_main"
type = "infisical"
api_base_url = "https://app.infisical.com"
client_id = "{$INFISICAL_CLIENT_ID}"
client_secret = "{$INFISICAL_CLIENT_SECRET}"
webhook_secret = "{$INFISICAL_WEBHOOK_SECRET}"
login_path = "/api/v1/auth/universal-auth/login"
secrets_path = "/api/v3/secrets/raw"
